-- Uniformizar unidades e stock final das embalagens Take Away
-- com base na contagem de 07-07-2026 (inventory-change-summary).

UPDATE inventory_items
SET
  unit = 'saco'
WHERE sku IN (
  'CONS-TAKEAWAY-SOUP-BOX-LID',
  'CONS-TAKEAWAY-BURGER-BOX',
  'CONS-TAKEAWAY-TOAST-BOX',
  'CONS-TAKEAWAY-BOX-750ML',
  'CONS-TAKEAWAY-ROUND-BOX-LID'
);

UPDATE inventory_items
SET
  "currentStock" = CASE sku
    WHEN 'CONS-TAKEAWAY-SOUP-BOX-LID'   THEN 15
    WHEN 'CONS-TAKEAWAY-BURGER-BOX'     THEN  5
    WHEN 'CONS-TAKEAWAY-TOAST-BOX'      THEN  5
    WHEN 'CONS-TAKEAWAY-BOX-750ML'      THEN 12
    WHEN 'CONS-TAKEAWAY-ROUND-BOX-LID'  THEN 20
  END
WHERE sku IN (
  'CONS-TAKEAWAY-SOUP-BOX-LID',
  'CONS-TAKEAWAY-BURGER-BOX',
  'CONS-TAKEAWAY-TOAST-BOX',
  'CONS-TAKEAWAY-BOX-750ML',
  'CONS-TAKEAWAY-ROUND-BOX-LID'
);

UPDATE inventory_items
SET
  "stockValue" = CASE sku
    WHEN 'CONS-TAKEAWAY-SOUP-BOX-LID'   THEN "costPrice" * 15
    WHEN 'CONS-TAKEAWAY-BURGER-BOX'     THEN "costPrice" *  5
    WHEN 'CONS-TAKEAWAY-TOAST-BOX'      THEN "costPrice" *  5
    WHEN 'CONS-TAKEAWAY-BOX-750ML'      THEN "costPrice" * 12
    WHEN 'CONS-TAKEAWAY-ROUND-BOX-LID'  THEN "costPrice" * 20
  END
WHERE sku IN (
  'CONS-TAKEAWAY-SOUP-BOX-LID',
  'CONS-TAKEAWAY-BURGER-BOX',
  'CONS-TAKEAWAY-TOAST-BOX',
  'CONS-TAKEAWAY-BOX-750ML',
  'CONS-TAKEAWAY-ROUND-BOX-LID'
);

